### ISSUE TITLE
Question par rapport au rover RTK

### ISSUE THREAD

**Issue by tdurand** [jancelin/centipede#3]
Bonjour, 

J'ai developpé une application très simple de guidage fonctionnant sous Android / iPhone: https://github.com/tdurand/tractornavigator 

Pour l'instant elle est fonctionnelle (sans grande précision) avec un telephone possédant un antenne dual frequency... Avec un Xiaomi mi 8 on arrive à avoir 1-2 m de précision... Suffisant pour un guidage basique..

L'objectif n'étant pas forcément de faire de l'autoguidage (et donc pas de necessité de RTK) mais plutôt de gagner en précision, avoir simplement une antenne dual frequency externe plus performante connecté en bluetooth pour avoir 0.5 - 1m de précision.. et pouvoir utiliser des téléphones / tablette ancienne juste pour l'interface.

Je suis tombé sur votre projet: https://jancelin.github.io/docs-centipedeRTK/docs/make_rover/ et je me demande si on fait le même setup mais sans connecter RTKGps a une base RTK, est-ce que cela fonctionnerai ? 

Merci et bravo pour ce projet ! 

Thibault

**Comment by jancelin** [comment]
Bonjour,

Oui ça fonctionne, il faut désactiver dans flux d'entrée> entrée base.
Dans ce cas la position est en single. Mais attention le sbas n'est pas actif il faut les rajouter au moment de l'injection des paramètres avec u-center.

**Comment by tdurand** [comment]
Ok, merci ! D'expérience vous pensez qu'on peut atteindre quelle précision sans appliquer les correctifs RTK avec cette antenne ?

**Comment by Stefal** [comment]
Je ne suis pas sûr que ça ait un grand intérêt vis à vis de la solution calculée en interne par le récepteur.
(sympa la vidéo du projet :-)  )

**Comment by tdurand** [comment]
@Stefal Merci ! 

Pour ce qui est de la précision, oui je ne pense pas que ça ameliore des masses en effet sans appliquer de correctifs... mais j'imagine que le fait d'avoir une antenne en extérieure (en dehors de la cabine) et également "plus puissante"  devrais rendre le truc plus fiable ?? _(en plus du fait que du coup on aurait pas besoin d'un telephone dernière generation avec puce double frequence et pourrait utiliser n'importe quelle tablette / telephone avec bluetooth)_

Après je sais pas si le fix de position que calcul Android fait des optimisations avec l'accelerometre en deplacement que du coup un système externe ne pourrait pas calculer... 

Evidemment si il est très simple de faire du RTK aussi pourquoi s'en priver ;-) .

**Comment by Stefal** [comment]
Désolé, je n'ai pas été très clair dans ma réponse.

A partir du moment où tu as un récepteur externe, avec son antenne de bonne qualité, tu peux : 
- Utiliser rtkgps+ pour récupérer les données 'raw' du récepteur, et faire faire les calculs à rtkgps+
- Utiliser directement les résultats de calcul de positionnement du récepteur externe.

Et ce que je voulais dire, c'est que je ne pense pas que rtkgps+ obtienne un meilleur résultat que le "moteur interne" du récepteur. Donc un récepteur externe avec une bonne antenne en liaison bluetooth avec un périf Android, me parait bien plus simple.

En cas de RTK, là c'est une tout autre histoire :-)

**Comment by wheintz** [comment]
Salut,

Sans appliquer de correction, la qualité de ta géolocalisation va dépendre uniquement de 2 choses :

**Comment by wheintz** [comment]
- la précision du signal émis
- la qualité de l'horloge de ton récepteur
En supposant évidemment que de bonnes conditions de réception soient respectées (horizon dégagé, éphéméride favorable ...)
Les récepteurs plus évolués proposent des algorithmes internes pour corriger d'éventuelles erreurs de trajet du signal reçu. L'utilisation d'une antenne dual aide aussi.
Du coup, si tu peux faire du RTK, il ne faut pas s'en priver !

**Comment by tdurand** [comment]
@Stefal  

merci pour la précision, oui en fait ce que je recherche c'est un dispositif externe Antenne  + traitement du signal (supportant double frequence et un max de constellations, au moins Galileo et GPS) qui ferait le calcul de position si possible sans avoir à passer par RtkGps+ .... et qui peut se connecter en bluetooth sur un dispositif Android.. Mais je ne trouve rien "tout fait" sur le marché, c'est pour cela que le travail fait ici m'interesse https://jancelin.github.io/docs-centipedeRTK/docs/make_rover/configuration.html .. 

@wheintz 

Merci, oui, en fait on s'est rendu compte que avec une antenne dual interne d'un smartphone et sans appliquer aucun correctif (en prenant le fix par defaut que donne android) c'était vraiment pas degueu c'est pour ça que l'on a fait l'appli.... Mais on aimerait améliorer encore et pouvoir faire fonctionner l'appli sur des telephones sans antennes dual (elle marche mais c'est l'horreur en précision).. d'où la recherche pour voir comment bricoler une antenne dual externe simple qui se connecterai en bluetooth.. (ou en acheter une si ça existe mais pas trouvé)

Et bien sur pour le RTK c'est sur que ça peut être beaucoup mieux, mais pour l'instant c'est vraiment beaucoup plus "lourd" necessitant 

- une base a laquelle pouvoir se connecter (generalement payant mais une belle initiative comme centipede pourrait rendre ça plus accessible)
- il faut du reseau 3g 

Donc beaucoup plus de chance que ça merde à un moment ou que ça ne marche pas.. l'idée de notre projet (pour l'instant) est de faire le systeme le plus "simple" et accessible possible avec une precision "OK" pour un guidage manuel (pas d'autopilote)

**Comment by wheintz** [comment]
C'est pour ça qu'on supporte à fond le projet de Julien ;-)

Dans quelle région es-tu Thibault ? Il y a de grandes chances qu'une antenne centipede soit installée prochainement pas loin de chez toi ! 

La nécessité du 3G est effectivement une limitation ... C'est le cas aussi pour nous dans le massif des Pyrénées. On essaye de trouver des solutions !

**Comment by tdurand** [comment]
Je suis en Creuse... Et la couverture 3g est pas top top dans certains endroits.. Oui pour s'affranchir de la 3g d'ailleurs je me demandais si la quantité de donnée émise par les bases pourrait être transmise via  Lora / LoraWan ?

**Comment by wheintz** [comment]
C'est ce qui est prévu par défaut sur les antennes Emlid qui sont livrées avec un module Lora... Mais nous ne sommes par en Amérique et on n'a malheureusment pas le droit de discuter en continu sur ces fréquences.

**Comment by jancelin** [comment]
oui c'est faisable avec un module qui correspond au normes de puissance française, l'important est de pouvoir emmettre en continue pour avoir une correction rtk qui fonctionne. donc il n'est pas possible d'emmettre fort (quelques 100ène de mètres à 1-2 km grand max en zone dégagé)
La fonction n'est pas disponible sur rtkbase mais c'est faisable. C'est le principe des bases mobiles et c'est prévu en dev prochainement.

**Comment by tdurand** [comment]
Je n'étais pas au courant des limitations reglementaire de l'utilisation des frequences Lora.. Bon par contre plutôt cool que l'on puisse au moins le faire dans un rayon limité.. mais oui c'est loin de mon usage car cela requiert encore un truc en plus à amener. 

Très intéressant en tout cas, merci pour toutes les infos. On va voir pour bricoler une antenne basée sur votre tutorial pour voir ce que ça donne.. et pourquoi pas par le futur mettre en service une base: https://jancelin.github.io/docs-centipedeRTK/docs/base/
