### ISSUE TITLE
Accès à la DB des bases ?

### ISSUE THREAD

**Issue by Fuzl** [jancelin/centipede#6]
Bonjour,

Afin de faire une sélection de base Centipede automatisée en fonction de la distance au point considéré j'aimerais avoir accès assez facilement à la DB des bases.
J'ai recherché dans le site sans succès. Est-ce que ce fichier est disponible ?

Merci et bravo pour ce très beau projet !

HC.

PS : Est-ce qu'un projet d'upgrade du rover en Bluetooth BLE pour être compatible avec iOS est envisagé ? C'est un objectif moyen terme auquel j'aimerais contribuer.

**Comment by Stefal** [comment]
Salut !
D'une certaine façon, tu as déjà accès à une base de données des stations de base : le caster, qui peut te renvoyer la "source table" avec toutes les bases et leurs coordonnées : http://[caster.centipede.fr:2101](http://caster.centipede.fr:2101/)/

Si jamais ça correspond à tes besoins, il y a https://github.com/CentipedeRTK/RtkBaseVar

Pour le rover, je crois qu'en BLE, c'est mort (avec iOs).
Tu peux en discuter sur le groupe telegram, ou bien sur le forum
https://t.me/Centipede_RTK
https://forum.geocommuns.fr/c/rtk-centipede

**Comment by Fuzl** [comment]
Parfait, merci pour la réponse !
